sudo: false
language: python
python: 3.4
env:
    - TOX_ENV=py34-django16
    - TOX_ENV=py34-django14
    - TOX_ENV=py34-django15
    - TOX_ENV=py34-django16
    - TOX_ENV=py34-django17
    - TOX_ENV=py34-django18
matrix:
    fast_finish: true
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
